/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafostp2.UI;

import grafos.Desenho.Graph;
import grafos.Desenho.Vertex;
import grafos.Desenho.Visualizar;
import grafostp2.Controlador.Controlador;
import grafostp2.EstruturaAuxiliares.Aresta;
import grafostp2.EstruturaAuxiliares.VerticeP;
import grafostp2.EstruturaDados.Lista;
import grafostp2.grafos.Grafos;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author gabriel
 */
public class GrafosTP1UI extends javax.swing.JFrame {

    private Controlador control;
    private Boolean representacao; //true lista//false matriz
    Visualizar view;
    /**
     * Creates new form GrafosTP1UI
     */
    public GrafosTP1UI() {
        initComponents();
        control = new Controlador();
        jComboBox1.setSelectedIndex(0);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        grupoRepresentacao = new javax.swing.ButtonGroup();
        grupoBusca = new javax.swing.ButtonGroup();
        grupoVerCaminho = new javax.swing.ButtonGroup();
        grupoAGM = new javax.swing.ButtonGroup();
        grupoMin = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        repInput = new javax.swing.JLabel();
        radioLista = new javax.swing.JRadioButton();
        radioMatriz = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultadoText = new javax.swing.JTextArea();
        input = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        root = new javax.swing.JPanel();
        inicioP = new javax.swing.JPanel();
        buscaP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        radioProfundidade = new javax.swing.JRadioButton();
        radioLargura = new javax.swing.JRadioButton();
        verticeInicialB = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        verCaminho = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        inicialVer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        finalVer = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        radioProfundidadeV = new javax.swing.JRadioButton();
        radioLarguraV = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        verConexo = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        alerta1 = new javax.swing.JLabel();
        agm = new javax.swing.JPanel();
        prim = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        kruskal = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        alerta2 = new javax.swing.JLabel();
        caminhoMin = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        radioDij = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        verMin = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        ordTopologica = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        entradaOrdT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        grafico = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto.setEditable(false);
        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(313, 50));

        repInput.setText("Representação do Grafo/Dígrafo");

        grupoRepresentacao.add(radioLista);
        radioLista.setText("Lista de Adjacência");
        radioLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioListaActionPerformed(evt);
            }
        });

        grupoRepresentacao.add(radioMatriz);
        radioMatriz.setText("Matriz");
        radioMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMatrizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioMatriz)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(repInput)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(repInput, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioLista)
                    .addComponent(radioMatriz)))
        );

        resultadoText.setEditable(false);
        resultadoText.setColumns(20);
        resultadoText.setRows(5);
        jScrollPane2.setViewportView(resultadoText);

        input.setText("Grafo/Dígrafo");

        jLabel4.setText("Resultados");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operações Grafos", "Busca", "Verificar Caminho", "Verificar se Grafo é Conexo", "Árvore Geradora Mínima", "Caminho Mínimo", "Coloração do Grafo", "Conectividade (Fortemente Conexas)", "Transposição Grafo", "Ordem Topológica" }));
        jComboBox1.setEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        root.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout inicioPLayout = new javax.swing.GroupLayout(inicioP);
        inicioP.setLayout(inicioPLayout);
        inicioPLayout.setHorizontalGroup(
            inicioPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        inicioPLayout.setVerticalGroup(
            inicioPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        root.add(inicioP, "inicioP");

        jLabel2.setText("Tipo da Busca");

        grupoBusca.add(radioProfundidade);
        radioProfundidade.setSelected(true);
        radioProfundidade.setText("Profundidade");

        grupoBusca.add(radioLargura);
        radioLargura.setText("Largura");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Vértice inicial da busca");

        javax.swing.GroupLayout buscaPLayout = new javax.swing.GroupLayout(buscaP);
        buscaP.setLayout(buscaPLayout);
        buscaPLayout.setHorizontalGroup(
            buscaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscaPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buscaPLayout.createSequentialGroup()
                        .addComponent(radioProfundidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioLargura))
                    .addGroup(buscaPLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(buscaPLayout.createSequentialGroup()
                        .addComponent(verticeInicialB, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(buscaPLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        buscaPLayout.setVerticalGroup(
            buscaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscaPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioProfundidade)
                    .addComponent(radioLargura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verticeInicialB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        root.add(buscaP, "buscaP");

        jLabel6.setText("Vértice Inicial");

        jLabel7.setText("Vértice Final");

        jButton2.setText("Verificar Caminho");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        grupoVerCaminho.add(radioProfundidadeV);
        radioProfundidadeV.setSelected(true);
        radioProfundidadeV.setText("Profundidade");
        radioProfundidadeV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioProfundidadeVActionPerformed(evt);
            }
        });

        grupoVerCaminho.add(radioLarguraV);
        radioLarguraV.setText("Largura");

        jLabel8.setText("Tipo de verificação");

        javax.swing.GroupLayout verCaminhoLayout = new javax.swing.GroupLayout(verCaminho);
        verCaminho.setLayout(verCaminhoLayout);
        verCaminhoLayout.setHorizontalGroup(
            verCaminhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verCaminhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioProfundidadeV)
                .addGap(34, 34, 34)
                .addComponent(radioLarguraV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(verCaminhoLayout.createSequentialGroup()
                .addGroup(verCaminhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verCaminhoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(finalVer, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(0, 176, Short.MAX_VALUE))
            .addGroup(verCaminhoLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inicialVer, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        verCaminhoLayout.setVerticalGroup(
            verCaminhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verCaminhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verCaminhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioProfundidadeV)
                    .addComponent(radioLarguraV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verCaminhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(verCaminhoLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(2, 2, 2)
                        .addComponent(finalVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(verCaminhoLayout.createSequentialGroup()
                        .addGroup(verCaminhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(inicialVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(34, 34, 34))))
        );

        root.add(verCaminho, "caminhoVer");

        jButton3.setText("Verificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Verificar se Grafo é conexo:");

        alerta1.setForeground(new java.awt.Color(255, 0, 0));
        alerta1.setText("Válido apenas para Grafos");

        javax.swing.GroupLayout verConexoLayout = new javax.swing.GroupLayout(verConexo);
        verConexo.setLayout(verConexoLayout);
        verConexoLayout.setHorizontalGroup(
            verConexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verConexoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(verConexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verConexoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(verConexoLayout.createSequentialGroup()
                        .addComponent(alerta1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        verConexoLayout.setVerticalGroup(
            verConexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verConexoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(verConexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(alerta1)
                .addContainerGap())
        );

        root.add(verConexo, "conexoVer");

        grupoAGM.add(prim);
        prim.setSelected(true);
        prim.setText("Prim");

        jLabel11.setText("Árvore Geradora Mínima");

        grupoAGM.add(kruskal);
        kruskal.setText("Kruskal");

        jButton4.setText("Gerar Árvore Mínima");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        alerta2.setForeground(new java.awt.Color(255, 0, 0));
        alerta2.setText("Válido apenas para Grafos");

        javax.swing.GroupLayout agmLayout = new javax.swing.GroupLayout(agm);
        agm.setLayout(agmLayout);
        agmLayout.setHorizontalGroup(
            agmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agmLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agmLayout.createSequentialGroup()
                .addComponent(prim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(agmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kruskal)
                    .addComponent(jButton4))
                .addContainerGap())
            .addGroup(agmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alerta2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agmLayout.setVerticalGroup(
            agmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agmLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prim)
                    .addComponent(kruskal))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alerta2))
        );

        root.add(agm, "agm");

        jLabel13.setText("Caminho Mínimo");

        grupoMin.add(radioDij);
        radioDij.setSelected(true);
        radioDij.setText("Dijkstra");

        grupoMin.add(jRadioButton2);
        jRadioButton2.setText("Bellman-Ford");

        jButton5.setText("Encontrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel14.setText("Vértice Inicial");

        javax.swing.GroupLayout caminhoMinLayout = new javax.swing.GroupLayout(caminhoMin);
        caminhoMin.setLayout(caminhoMinLayout);
        caminhoMinLayout.setHorizontalGroup(
            caminhoMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caminhoMinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(caminhoMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(caminhoMinLayout.createSequentialGroup()
                        .addComponent(radioDij)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton2)
                        .addGap(38, 38, 38))
                    .addGroup(caminhoMinLayout.createSequentialGroup()
                        .addGroup(caminhoMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(caminhoMinLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(caminhoMinLayout.createSequentialGroup()
                                .addComponent(verMin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(jButton5)))
                        .addContainerGap())
                    .addGroup(caminhoMinLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        caminhoMinLayout.setVerticalGroup(
            caminhoMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caminhoMinLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(caminhoMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioDij)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(4, 4, 4)
                .addGroup(caminhoMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        root.add(caminhoMin, "verMin");

        jTextPane1.setText("\n\n\t              TRABALHO PRÁTICO I\n\t               Teoria dos Grafos\n\n          Professor Danilo Medeiros Eler\n          \n          Diovanni Gregorio Ferraro dos Santos\n          Gabriel de Oliveira Almeida\n          Joao Victor Silva Menezes\n\n"); // NOI18N
        jTextPane1.setFocusable(false);
        jTextPane1.setOpaque(false);
        jTextPane1.setRequestFocusEnabled(false);
        jScrollPane4.setViewportView(jTextPane1);

        root.add(jScrollPane4, "card8");

        jLabel1.setText("Vertice Inicial");

        jButton7.setText("Ordenar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        entradaOrdT.setText(" ");
        entradaOrdT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaOrdTFocusGained(evt);
            }
        });

        jLabel10.setText("Ordenação Topologica");

        javax.swing.GroupLayout ordTopologicaLayout = new javax.swing.GroupLayout(ordTopologica);
        ordTopologica.setLayout(ordTopologicaLayout);
        ordTopologicaLayout.setHorizontalGroup(
            ordTopologicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordTopologicaLayout.createSequentialGroup()
                .addGroup(ordTopologicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ordTopologicaLayout.createSequentialGroup()
                        .addComponent(entradaOrdT, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addGroup(ordTopologicaLayout.createSequentialGroup()
                        .addGroup(ordTopologicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ordTopologicaLayout.setVerticalGroup(
            ordTopologicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordTopologicaLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addGroup(ordTopologicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ordTopologicaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(entradaOrdT))
                    .addGroup(ordTopologicaLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );

        root.add(ordTopologica, "ordTopol");

        jLabel3.setText("Representação");

        jButton6.setText("Grafo Inicial");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jMenu1.setText("Grafo (Arquivo)");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Carregar Grafo (Arquivo)");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Modificar Grafo (Arquivo)");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator1);

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(input)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grafico)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(input)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grafico)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here: 
        view = new Visualizar();
        String impressao;
        if(!control.pegaArquivo()) return;
        texto.setText("");
        resultadoText.setText("");
        control.inicializar();
        view.setGraph(control.getGraph());
        grafico.getViewport().add(view);
        //javax.swing.JScrollPane j = new javax.swing.JScrollPane(this.view);
        jComboBox1.setEnabled(true);
        jComboBox1.requestFocus();
        resultadoText.setText("");
        if (radioLista.isSelected()) {
            impressao = control.imprimirLista();
        } else if (radioMatriz.isSelected()) {
            impressao = control.imprimirMatriz();
        } else {
            impressao = "";
        }
        if (control.getOr() == 1) {
            input.setText("Dígrafo");
            repInput.setText("Representação Dígrafo");
            alerta1.setVisible(true);
            alerta2.setVisible(true);
        } else {
            input.setText("Grafo");
            repInput.setText("Representação Grafo");
            alerta1.setVisible(false);
            alerta2.setVisible(false);
            
        }
        texto.setText(impressao);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void radioListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioListaActionPerformed
        // TODO add your handling code here:
        texto.setText(control.imprimirLista());
        representacao = true;
    }//GEN-LAST:event_radioListaActionPerformed

    private void radioMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMatrizActionPerformed
        // TODO add your handling code here:
        texto.setText(control.imprimirMatriz());
        representacao = false;
    }//GEN-LAST:event_radioMatrizActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int qual = jComboBox1.getSelectedIndex();
        CardLayout c = (CardLayout) root.getLayout();

        switch (qual) {
            case 0:
                c.show(root, "inicioP");
                break;
            case 1:
                c.show(root, "buscaP");
                break;
            case 2:
                c.show(root, "caminhoVer");
                break;
            case 3:
                c.show(root, "conexoVer");
                break;
            case 4:
                c.show(root, "agm");
                break;
            case 5:
                c.show(root, "verMin");
                break;
            case 9:
                c.show(root, "ordTopol");
                break;
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed
    private void resetCampo(javax.swing.JTextField campo) {
        campo.setText("");
        campo.requestFocus();
    }

    private Boolean repres() {
        if (!(radioLista.isSelected() || radioMatriz.isSelected())) {
            JOptionPane.showMessageDialog(null, "Escolha qual representação do Grafo/Dígrafo, "
                    + "e tente novamente.","ATENÇÃO", WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        inicial();
        int inicial;
        int[] vet = new int[Grafos.tam];
        String impressao;
        if (!repres()) {
            return;
        }
        try {
            inicial = Integer.parseInt(verticeInicialB.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Entrada inválida","ERRO", ERROR_MESSAGE);
            verticeInicialB.setText("");
            verticeInicialB.requestFocus();
            return;
        }
        if (!control.verificarEntrada(inicial)) {
            JOptionPane.showMessageDialog(null, "Entrada inválida","ERRO", ERROR_MESSAGE);
            resetCampo(verticeInicialB);
            return;
        }
        if (!control.verificarEntrada(inicial)) {
            return;
        }
        if (radioProfundidade.isSelected()) {
            impressao = control.buscaProfundidadeString(inicial, representacao);
            resultadoText.setText(impressao);
        } else {
            impressao = control.buscaLarguraString(vet, inicial, representacao);
            view.pintarArestas(vet);
            resultadoText.setText(impressao);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        inicial();
        if (!repres()) {
            return;
        }
        int inicio = 0, fim, tam;
        Boolean existe;
        String cami;
        String impressao = "";
        ArrayList<String> lista = new ArrayList<>();
        CardLayout c = (CardLayout) root.getLayout();
        try {
            inicio = Integer.parseInt(inicialVer.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Entrada inválida","ERRO", ERROR_MESSAGE);
            resetCampo(inicialVer);
            return;
        }
        try {
            fim = Integer.parseInt(finalVer.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Entrada inválida","ERRO", ERROR_MESSAGE);
            resetCampo(finalVer);
            return;
        }
        if (!(control.verificarEntrada(inicio) && control.verificarEntrada(fim))) {
            JOptionPane.showMessageDialog(null, "Entrada inválida ","ERRO", ERROR_MESSAGE);
            resetCampo(finalVer);
            resetCampo(inicialVer);
            return;
        }
        if (radioProfundidadeV.isSelected()) {
            //impressao += control.buscaProfundidadeString(inicio, representacao);
            lista = control.verificarCaminho(inicio, fim, representacao, true);
            if (lista != null) {
                view.caminho(lista);
                cami = String.join("-> ", lista);
                cami = impressao + "Busca Profundidade:\n" + cami;
                resultadoText.setText(cami);
            } else {
                cami = "Busca Largura:\n" + "Caminho Não Encontrado";
                resultadoText.setText(cami);
            }
        } else {
            lista = control.verificarCaminho(inicio, fim, representacao, false);
            if (lista != null) {
                view.caminho(lista);
                cami = String.join("-> ", lista);
                cami = "Busca Largura:\n" + cami;
                resultadoText.setText(cami);
            } else {
                cami = "Busca Largura:\n" + "Caminho Não Encontrado";
                resultadoText.setText(cami);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        String arq = control.modificarArquivo();
        if(arq == null) return;
        GrafosArqUI principal = new GrafosArqUI(arq);
        principal.requestFocus();
        principal.setVisible(true);


    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void radioProfundidadeVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioProfundidadeVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioProfundidadeVActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       inicial();
        String impressao;
        
        if (!repres()) {
            return;
        }
        int[] comp = new int[Grafos.tam];
        if (control.getOr() == 1) {
            JOptionPane.showMessageDialog(null, "Válido apenas para Grafos!", "ATENÇÃO", WARNING_MESSAGE);
        } else {
            impressao = control.buscaProfundidadeConexo(comp, representacao);
            view.compConexas(comp);
            resultadoText.setText(impressao);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        inicial();
        ArrayList<Aresta> impressao;
        if (!repres()) {
            return;
        }
        if (control.getOr() == 1) {
            JOptionPane.showMessageDialog(null, "Válido apenas para Grafos!","ATENÇÃO", WARNING_MESSAGE);
            return;
        }
        if (kruskal.isSelected()) {
            impressao = control.agmKruskal(representacao);
        } else {
            impressao = control.agmPrim(representacao);
        }
        view.arvoreGeradora(impressao);
        String resul="Vertice1 Vertice2 (Peso)\n";
        for(Aresta a:impressao){
            resul+=String.valueOf(a.getVer1())+" "+ String.valueOf(a.getVer2())+
                    " ("+a.getPeso()+")"+"\n";
        }
            
        
        resultadoText.setText(resul);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        inicial();
        int inicial;
        if (!repres()) {
            return;
        }
        try {
            inicial = Integer.parseInt(verMin.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Entrada Inválida","ERRO", ERROR_MESSAGE);
            resetCampo(verMin);
            return;
        }
        if (!control.verificarEntrada(inicial)) {
            JOptionPane.showMessageDialog(null, "Entrada Inválida", "ERRO", ERROR_MESSAGE);
            resetCampo(verMin);
            return;
        }
        //String caminho;
        Lista[] caminho;
        if (radioDij.isSelected()) {
            caminho = control.dijkstra(representacao,inicial);
            view.caminhoMin(caminho);  
        } else {
            caminho = control.bellman(representacao, inicial);
            view.caminhoMin(caminho); 
        }
        resultadoText.setText(imprimirLista(caminho));
    }//GEN-LAST:event_jButton5ActionPerformed

    private String imprimirLista(Lista[] lista){
        int i,j, tamanho;
        String resul = "Vertice\tCaminho\n";
        for(i=0; i<Grafos.tam; i++){
            tamanho = lista[i].size();
            resul += String.valueOf(i) + "|\t";
            for(j=0 ; j<tamanho; j++){
                resul+= String.valueOf(lista[i].getVer(j))+ "->";
            }
            resul+="/\n";
        }
        return resul;
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        inicial();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        inicial();
        int inicial;
        if (!repres()) {
            return;
        }
        try {
            inicial = Integer.parseInt(entradaOrdT.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Entrada Inválida","ERRO", ERROR_MESSAGE);
            resetCampo(entradaOrdT);
            return;
        }
        if (!control.verificarEntrada(inicial)) {
            JOptionPane.showMessageDialog(null, "Entrada inválida","ERRO", ERROR_MESSAGE);
            resetCampo(entradaOrdT);
            return;
        }
        ArrayList<VerticeP> vert = control.ordTopologica(representacao, inicial);
        view.ordTopologica(vert);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void entradaOrdTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaOrdTFocusGained
        // TODO add your handling code here:
        entradaOrdT.setText("");
    }//GEN-LAST:event_entradaOrdTFocusGained

    private void inicial(){
      view.setEdgesTrueFalse(true);
      view.setCor();
      view.setEdgesTrueFalse(false);
      view.cleanImage();
      view.repaint();  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrafosTP1UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrafosTP1UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrafosTP1UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrafosTP1UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrafosTP1UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agm;
    private javax.swing.JLabel alerta1;
    private javax.swing.JLabel alerta2;
    private javax.swing.JPanel buscaP;
    private javax.swing.JPanel caminhoMin;
    private javax.swing.JTextField entradaOrdT;
    private javax.swing.JTextField finalVer;
    private javax.swing.JScrollPane grafico;
    private javax.swing.ButtonGroup grupoAGM;
    private javax.swing.ButtonGroup grupoBusca;
    private javax.swing.ButtonGroup grupoMin;
    private javax.swing.ButtonGroup grupoRepresentacao;
    private javax.swing.ButtonGroup grupoVerCaminho;
    private javax.swing.JTextField inicialVer;
    private javax.swing.JPanel inicioP;
    private javax.swing.JLabel input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton kruskal;
    private javax.swing.JPanel ordTopologica;
    private javax.swing.JRadioButton prim;
    private javax.swing.JRadioButton radioDij;
    private javax.swing.JRadioButton radioLargura;
    private javax.swing.JRadioButton radioLarguraV;
    private javax.swing.JRadioButton radioLista;
    private javax.swing.JRadioButton radioMatriz;
    private javax.swing.JRadioButton radioProfundidade;
    private javax.swing.JRadioButton radioProfundidadeV;
    private javax.swing.JLabel repInput;
    private javax.swing.JTextArea resultadoText;
    private javax.swing.JPanel root;
    private javax.swing.JTextArea texto;
    private javax.swing.JPanel verCaminho;
    private javax.swing.JPanel verConexo;
    private javax.swing.JTextField verMin;
    private javax.swing.JTextField verticeInicialB;
    // End of variables declaration//GEN-END:variables
}
